[package]
name = "clspv-sys"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["shader", "compiler", "spirv", "opencl"]

[lib]
name = "clspv_sys"

[features]
build-from-source = []

[build-dependencies]
cmake = "0.1"
